name: Daily cron jobs 

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  push:
    branches: 
      - main

jobs:
  backup-sukusukuseparuh:
    name: Backup SukuSukuSeparuh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Run script
        run: ./scripts/backup-sukusukuseparuh.sh
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}